driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.5
    run_list: apt::default
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[iptables_test::default]
    attributes:
      iptables:
        iptables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
        ip6tables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
  - name: disabled
    run_list:
      - recipe[iptables::disabled]
  - name: no_template
    run_list:
      - recipe[iptables_test::no_template]
    attributes:
      iptables:
        iptables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
        ip6tables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
  - name: nested
    run_list:
      - recipe[iptables_test::nested]
    attributes:
      iptables:
        iptables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
        ip6tables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
