driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-8
    run_list: apt::default
  - name: debian-9
    run_list: apt::default
  - name: fedora-27
  - name: opensuse-leap-42
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[iptables_test::default]
    attributes:
      iptables:
        iptables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
        ip6tables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
  - name: disabled
    run_list:
      - recipe[iptables::disabled]
  - name: no_template
    run_list:
      - recipe[iptables_test::no_template]
    attributes:
      iptables:
        iptables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
        ip6tables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
  - name: nested
    run_list:
      - recipe[iptables_test::nested]
    attributes:
      iptables:
        iptables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
        ip6tables_sysconfig:
          IPTABLES_STATUS_VERBOSE: 'yes'
